const CALL_POLLING_INTERVAL = 60000  // one minute
const DEFAULT_NOFITY_MILLISECONDS = 1800000  // thirty minutes
// const REDIAL_DELAY_MILLISECONDS = 180000 
const FROM_NUMBER_VONAGE = "972526548353"  // vonage number 
const CALENDAR_POLL_INTERVAL = 3000  // three seconds
const REDIAL_DELAY_MILLISECONDS = 180000  // three minutes

module.exports = {
    CALL_POLLING_INTERVAL,
    DEFAULT_NOFITY_MILLISECONDS,
    REDIAL_DELAY_MILLISECONDS,
    FROM_NUMBER_VONAGE,
    CALENDAR_POLL_INTERVAL,  // three seconds
}